imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
fos_twitter:
    file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key: Huzq3JiVnckweiDIDlhpxg
    consumer_secret: 5bNkZddwISgRSZIKMP1LGAuKECyKN04SZ4cBsiRkhr0
    callback_url: http://netagora.hugohamon.com/twitter/login_check

#my.twitter.user:
#    class: ECE\netagoraBundle\Security\User\Provider\TwitterProvider
#    arguments:
#        twitter_oauth: "@fos_twitter.api"
#        userManager: "@fos_user.user_manager"
#        validator: "@validator"
#        session: "@session"

fos_facebook:
    file: %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias: facebook
    app_id: 157952174313665
    secret: 9c3f8ab5c7d332bbdaccbbb8d9823a0d
    cookie: true
    permissions: [email, read_stream]

fos_user:
    db_driver:     orm
    firewall_name: main
    use_listener: false
    user_class:   ECE\Bundle\NetagoraBundle\Entity\User
    
    