ECE\netagoraBundle\Entity\Fb:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    user:
      type: string
      length: 255
    token:
      type: text
    fb_id:
      type: string
      length: '200'
  lifecycleCallbacks: {  }
