ECE\netagoraBundle\Entity\Publications:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    user:
      type: string
      length: '200'
    known_link:
      type: string
      length: 255
    network:
      type: integer
    author:
      type: string
      length: '200'
    date_published:
      type: datetime
    publication_ref:
      type: string
      length: '200'
    content:
      type: text
    link_url:
      type: string
      length: '200'
  lifecycleCallbacks: {  }
