ECE\netagoraBundle\Entity\Twitter:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    user:
      type: string
      length: 255
    token:
      type: string
      length: '200'
    twitter_id:
      type: integer
  lifecycleCallbacks: {  }
