ECE\netagoraBundle\Entity\User:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
#    username:
#      type: string
#      length: 255
#    email:
#      type: string
#      length: 255
#    password:
#      type: string
#      length: 255
    picture:
      type: string
      length: 70
      nullable: true
    location:
      type: string
      length: 100
      nullable: true
    firstname:
      type: string
      length: 100
      nullable: true
    lastname:
      type: string
      length: 100
      nullable: true
    birthdate:
      type: date
      nullable: true
    inscriptionDate:
      type: datetime
      nullable: true
    lastConnection:
      type: datetime
      nullable: true
  lifecycleCallbacks: {  }
