homepage:
    pattern: /
    defaults: { _controller: "ECEBetaBundle:Default:index" }
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal