favoris:
    pattern:  /
    defaults: { _controller: "netagoraBundle:Favoris:index" }

favoris_show:
    pattern:  /{id}/show
    defaults: { _controller: "netagoraBundle:Favoris:show" }

favoris_new:
    pattern:  /new
    defaults: { _controller: "netagoraBundle:Favoris:new" }

favoris_create:
    pattern:  /create
    defaults: { _controller: "netagoraBundle:Favoris:create" }
    requirements: { _method: post }

favoris_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "netagoraBundle:Favoris:edit" }

favoris_update:
    pattern:  /{id}/update
    defaults: { _controller: "netagoraBundle:Favoris:update" }
    requirements: { _method: post }

favoris_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "netagoraBundle:Favoris:delete" }
    requirements: { _method: post }
