publications:
    pattern:  /
    defaults: { _controller: "netagoraBundle:Publications:index" }

publications_show:
    pattern:  /{id}/show
    defaults: { _controller: "netagoraBundle:Publications:show" }

publications_new:
    pattern:  /new
    defaults: { _controller: "netagoraBundle:Publications:new" }

publications_create:
    pattern:  /create
    defaults: { _controller: "netagoraBundle:Publications:create" }
    requirements: { _method: post }

publications_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "netagoraBundle:Publications:edit" }

publications_update:
    pattern:  /{id}/update
    defaults: { _controller: "netagoraBundle:Publications:update" }
    requirements: { _method: post }

publications_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "netagoraBundle:Publications:delete" }
    requirements: { _method: post }
