publication_history:
    pattern:  /
    defaults: { _controller: "netagoraBundle:Publication_history:index" }

publication_history_show:
    pattern:  /{id}/show
    defaults: { _controller: "netagoraBundle:Publication_history:show" }

publication_history_new:
    pattern:  /new
    defaults: { _controller: "netagoraBundle:Publication_history:new" }

publication_history_create:
    pattern:  /create
    defaults: { _controller: "netagoraBundle:Publication_history:create" }
    requirements: { _method: post }

publication_history_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "netagoraBundle:Publication_history:edit" }

publication_history_update:
    pattern:  /{id}/update
    defaults: { _controller: "netagoraBundle:Publication_history:update" }
    requirements: { _method: post }

publication_history_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "netagoraBundle:Publication_history:delete" }
    requirements: { _method: post }
